# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: App Build & Push

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  python-pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} üêç
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements ‚è¨
      run: |
        echo "--- Installing PIP"
        python -m pip install --upgrade pip
        echo "--- Installing PyTest prerequisites"
        pip install pytest flake8 cryptography
        echo "--- Installing requirements"
        if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

    - name: Lint with flake8 üìù
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "--- Linting with flake8"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with PyTest ‚öôÔ∏è
      env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GUNICORN_CHDIR: ${{ secrets.GUNICORN_CHDIR }}
      run: |
        echo "--- Starting app in background"
        python3 code/app.py &
        echo "--- Sleep(3)"
        sleep 3
        echo "--- Starting PyTest"
        pytest code/tests


  python-build:
    runs-on: ubuntu-latest
    needs:
    - python-pytest
    if: ${{ needs.python-pytest.result == 'success' }}

    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v4

    - name: Log in to Docker Hub üîê
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extracting Metadata üîß
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=,suffix=,format=short
          type=edge
          type=raw,value=latest

    - name: Build & Push to Docker Hub üöÄ
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./python/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
